---
- name: install docker and deploy containers
  hosts: all
  become: yes
  tasks:

    - name: install docker
      yum:
        name: docker
        state: present
       
    - name: start docker service
      service:
        name: docker
        state: started

    - name: check /opt/app directory exists
      file:
        path: /opt/app
        state: directory
        mode: '0755'

    - name: copy Dockerfile for deployment
      copy:
        src: /home/ec2-user/jenkins/jenkins/workspace/ansible/Dockerfile
        dest: /opt/app/Dockerfile
        owner: root
        group: root

    - name: copy WAR file
      copy:
        src: /home/ec2-user/jenkins/jenkins/workspace/ansible/target/petshop.war
        dest: /opt/app/petshop.war
        owner: root
        group: root

    - name: build docker image from Dockerfile
      community.docker.docker_image:
        name: narasimha
        source: build        # ✅ this line is required
        build:
          path: /opt/app     # ✅ correct build context
        state: present
     
    - name: remove existing containers
      community.docker.docker_container:
        name: "naidu{{ item }}"
        state: absent
      loop:
        - 1
        - 2
        - 3

    - name: create containers
      community.docker.docker_container:
        name: "naidu{{ item }}"
        image: narasimha
        ports:
          - "808{{ item }}:8080"
        state: started
      loop:
        - 1
        - 2
        - 3
