---
- name: install docker and deploye with containers
  hosts: all
  become: yes
  tasks:
   - name: install docker
     yum:
       name: docker
       state: present
       
   - name: start docker service
     service:
        name: docker
        state: started

   - name: directory exists
     file:
        path: /opt/app
        state: directory
        mode: '0755'
   - name: copy docker file and war file for deployment
     copy:
          src: /home/ec2-user/jenkins/jenkins/workspace/ansible/Dockerfile
          dest: /opt/app/Dockerfile
          owner: root
          group: root

   - name: copying war file
     copy:
         src: /home/ec2-user/jenkins/jenkins/workspace/ansible/target/petshop.war
         dest: /opt/app/petshop.war
   - name: docker image building from Dockerfile
     community.docker.docker_image:
         name: narasimha
         path: /opt/app/
         state: present
     
   - name: rempove existing containers
     docker_container:
         name: "naidu{{ item }}"
         state: absent
     loop:
         - 1
         - 2
         - 3
   - name: creating containers
     docker_container:
          name: "naidu{{ item }}"
          image: narasimha
          ports:
             - "808{{ item }}:8080"
          state: started
     loop:
         - 1
         - 2
         - 3
